name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_github
          chmod 600 ~/.ssh/github_deploy_key
          ssh-keyscan -H 35.78.20.87 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/github_deploy_key ubuntu@35.78.20.87 << EOF
            cd /opt/goapp/src
            bash deploy.sh
          EOF
