name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$AWS_ACCESS_KEY_ID" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          ssh-keyscan -H <EC2_IP> >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          ssh -i ~/.ssh/id_github ubuntu@35.78.20.87 << EOF
            cd /opt/goapp/src
            bash deploy.sh
          EOF
